---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Termekek
- type: directory
  path: cms/termekek
  label: Fenyezofulke termekek
  create: all
  match: "**/*"
  templates:
  - termekeink
- type: heading
  label: Content
- type: directory
  path: cms/posts
  label: Posts
  create: all
  match: "**/*.md"
  templates:
  - cikk-withbigcontentarea-template
- type: directory
  path: cms/references
  label: References
  create: all
  match: "**/*"
  templates:
  - reference-gallery
  - referencia
- type: heading
  label: Pages
- type: directory
  path: cms/pages
  label: Home
  create: all
  match: "**/*"
upload_dir: public/uploads
public_path: "/public/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
