---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Termekek
- type: directory
  path: cms/termekek/fenyezofulkek
  label: Fenyezofulke termekek
  create: documents
  match: "**/*"
  templates:
  - termekeink
- type: directory
  path: cms/termekek/feluletkezeles
  label: Ipari feluletkezeles termekek
  create: all
  match: "**/*"
  templates:
  - ipari-feluletkezeles-termek
- type: directory
  path: cms/termekek/tuzelestechnika
  label: Tuzelestechnika
  create: all
  match: "**/*"
  templates:
  - tuzelestechnika-termek
- type: directory
  path: cms/termekek/szorastechnika
  label: Szorastechnika
  create: all
  match: "**/*"
  templates:
  - szorastechnika-termek
- type: heading
  label: Content
- type: directory
  path: cms/posts
  label: Posts
  create: all
  match: "**/*.md"
  templates:
  - cikk-withbigcontentarea-template
- type: directory
  path: cms/references
  label: References
  create: all
  match: "**/*"
  templates:
  - reference-gallery
  - referencia
- type: heading
  label: Pages
- type: directory
  path: cms/pages
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: cms/kapcsolat
  label: Kapcsolat
  create: all
  match: "**/*"
  templates:
  - kapcsolat-egyen
upload_dir: public/uploads
public_path: "/public/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
