---
label: services
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: title
- name: subtitle
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: subtitle
- name: fenyezo-description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: fenyezo-description
- name: szoras-desc
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: szoras-desc
- name: tuzeles-desc
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: tuzeles-desc
- name: felulet-desc
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: felulet-desc
